[project]
name = "mkdocs-website-template"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "mkdocs-material[imaging]>=9.6.9",
    "pycairo >= 1.28.0"
]
