authors:
  daveebbelaar:
    name: Marco Berta
    description: AI Engineer & Data Scientist
    avatar: https://avatars.githubusercontent.com/u/52595223?v=4
    url: https://www.linkedin.com/in/marco-berta/